Simplify handling generators in json renderer
cloudblue/connect-reports-core pull request #29
Opened 2021-05-17 11:20 UTC by effrenus

2021-05-17 12:43 UTC, marcserrat requested changes

2021-05-17 12:43 UTC, marcserrat commented on connect/reports/renderers/json.py
> +                    if sep == b'': sep = b','
please check linting

2021-05-18 11:07 UTC, ffaraoneim reviewed
In terms of clarity, I don't see a big difference between the two implementations. Do you see any other benefit/improvement merging this change ?
Thanks!

2021-05-18 11:46 UTC, effrenus commented
> In terms of clarity, I don't see a big difference between the two implementations. Do you see any other benefit/improvement merging this change ?

For me code below too cryptic, so wanted to share alternative.

https://github.com/cloudblue/connect-reports-core/blob/ff3728e4bbe52db620d8329f3540e03a140d622b/connect/reports/renderers/json.py#L33-L35

Will close PR.

PS. Just out of curiosity, why you switched to `orjson`? Thx.

2021-05-18 11:46 UTC, closed without merging